- name: Deploy to Charmander
  hosts: charmander
  strategy: linear
  tasks:
    - name: Publish package # noqa: run-once[task]
      delegate_to: localhost
      ansible.builtin.command: dotnet publish -c Release -r linux-arm64 --no-self-contained -o OwenBot/bin/publish OwenBot
      changed_when: false
      run_once: true
    - name: Copy executable
      ansible.builtin.copy:
        src: OwenBot/bin/publish/OwenBot
        dest: /usr/local/bin/OwenBot
        mode: "0755"
      notify:
        - Restart service
    - name: Write Unit File
      ansible.builtin.template:
        src: templates/owenbot.service.j2
        dest: /etc/systemd/system/owenbot.service
        mode: "0755"
      vars:
        discord_api_token: "{{ lookup('community.general.bitwarden', 'OwenBot', field='DiscordApiToken') }}"
      notify:
        - Restart service
  handlers:
    - name: Restart service
      ansible.builtin.systemd:
        name: owenbot.service
        state: restarted
        enabled: true
        daemon_reload: true

