name: build

on:
  push:
    branches:
      - "master"

permissions:
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAGS: ${{ github.run_number }}-${{ github.sha }} latest

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-path: ${{ steps.push.registry-path }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install -y qemu-user-static podman

      - name: Build images with Buildah
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/arm64, linux/amd64
          layers: true
          containerfiles: |
            ./Dockerfile

      - name: Push image and tags to registry
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
